# inspect cards

In [47]:
import pymongo
import pandas as pd
from pytz import timezone
from bson.codec_options import CodecOptions
import matplotlib.pyplot as plt
from pymongo import MongoClient

#global const's
WEEKS = 8
TIMESTAMPS_PER_HOUR = 2
#global var's
local_client = MongoClient('localhost', 27017)
coll = local_client.admin.passwords
doc = coll.find_one({"key":"MONGOMLAB"})
mongopass = doc["value"]
trello_key,trello_token = (local_client.admin.passwords.find_one({"key":k})["value"] for k in ["TRELLOKEY","TRELLOTOKEN"])

In [19]:
import requests
import json

url_stem = "https://api.trello.com"
url = f"{url_stem}/1/tokens/{trello_token}/member"

headers = {
   "Accept": "application/json"
}

query = {
   'key': trello_key,
   'token': trello_token
}

response = requests.request(
   "GET",
   url,
   headers=headers,
   params=query
)

board_ids = json.loads(response.text)["idBoards"]

In [21]:
boards = {b:json.loads(requests.request("GET",f"{url_stem}/1/boards/{b}",headers=headers,params=query).text) for b in board_ids}

In [84]:
import pandas as pd
board_id = "5b9a8552aa36733037ae917e"
lists = {l["id"]:l for l in json.loads(requests.request("GET",f"{url_stem}/1/boards/{board_id}/lists",headers=headers,params={**query,"filter":"all"}).text)}
pd.DataFrame(lists.values())

,id,name,closed,pos,softLimit,idBoard,subscribed
0,5b9a88e3dcd6f9892f47c372,PENDING,False,65535,None,5b9a8552aa36733037ae917e,False
1,5ba121d9717eb68f1713243a,todo,False,81919,None,5b9a8552aa36733037ae917e,False
2,5b9deba8298b842b75c2de29,TODO,False,98303,None,5b9a8552aa36733037ae917e,False
3,5b9e84eb6bd99d50eea0ab64,SPORT,True,114687,None,5b9a8552aa36733037ae917e,False
4,5b9a88e55dd1b019f077c978,DONE,True,131071,None,5b9a8552aa36733037ae917e,False
5,5b9e84f72c2644393805a0cc,einsoch,True,163839,None,5b9a8552aa36733037ae917e,False
6,5bfd1098ffe7563e41e81f69,FAILED2,False,172031,None,5b9a8552aa36733037ae917e,False
7,5b9ef2afac2bb38effad88ed,FAILED,False,196607,None,5b9a8552aa36733037ae917e,False

In [115]:
list_id = "5ba121d9717eb68f1713243a"
cards = {l["id"]:l for l in json.loads(requests.request("GET",f"{url_stem}/1/lists/{list_id}/cards",headers=headers,params=query).text)}

In [142]:
import pandas as pd
import re

_df = pd.DataFrame([c for c in cards.values() if re.match("fix good day, sleep",c["name"]) is not None])
_df if _df.size==0 else _df.loc[:,["id","name","dateLastActivity","shortUrl"]]

,id,name,dateLastActivity,shortUrl
0,5de05753f2335132bc9c335e,"fix good day, sleep",2020-02-02T14:59:42.942Z,https://trello.com/c/bwLo6BBc

In [143]:
for i in _df["id"]:
    res = requests.request("PUT",f"{url_stem}/1/cards/{i}",headers=headers,params={**query,"closed":"true"}).text
    print(f"{i} => {res}")

5de05753f2335132bc9c335e => {"id":"5de05753f2335132bc9c335e","checkItemStates":[],"closed":true,"dateLastActivity":"2020-07-01T08:35:39.947Z","desc":"","descData":null,"dueReminder":null,"idBoard":"5b9a8552aa36733037ae917e","idList":"5ba121d9717eb68f1713243a","idMembersVoted":[],"idShort":16048,"idAttachmentCover":null,"idLabels":["5c36a78df1a04f871b765f6c"],"manualCoverAttachment":false,"name":"fix good day, sleep","pos":139678464,"shortLink":"bwLo6BBc","isTemplate":false,"dueComplete":false,"due":null,"email":null,"shortUrl":"https://trello.com/c/bwLo6BBc","url":"https://trello.com/c/bwLo6BBc/16048-fix-good-day-sleep","cover":{"idAttachment":null,"color":null,"idUploadedBackground":null,"size":"normal","brightness":"light"},"idMembers":[],"badges":{"attachmentsByType":{"trello":{"board":0,"card":0}},"location":false,"votes":0,"viewingMemberVoted":false,"subscribed":false,"fogbugz":"","checkItems":0,"checkItemsChecked":0,"checkItemsEarliestDue":null,"comments":0,"attachments":0,"description":false,"due":null,"dueComplete":false},"subscribed":false,"idChecklists":[],"labels":[{"id":"5c36a78df1a04f871b765f6c","idBoard":"5b9a8552aa36733037ae917e","name":"gym","color":null}]}

# fix mongo
## habits

In [63]:
client = MongoClient(f"mongodb://nailbiter:{mongopass}@ds149672.mlab.com:49672/logistics?retryWrites=false")

In [138]:
import pandas as pd
timecoll = client.logistics["alex.habitspunch"].with_options(codec_options=CodecOptions(tz_aware=True,tzinfo=timezone('Asia/Tokyo')))
habitspunch_df = pd.DataFrame([r for r in timecoll.find().sort("date",pymongo.DESCENDING)])

In [140]:
from datetime import datetime, timedelta
dates = {"2019-11-29"}
_FORMAT = "%Y-%m-%d"
_dates = {*dates,*{(datetime.strptime(ds,_FORMAT)+timedelta(days=1)).strftime(_FORMAT) for ds in dates}}

_df = pd.DataFrame(
    [r 
     for r 
     in habitspunch_df.to_dict(orient="records") 
     if r["name"] in ["good day","sleep"] 
         and r["date"].strftime("%Y-%m-%d") in _dates
         and r["status"]=="FAILURE"
    ])
_df if _df.size==0 else _df.set_index("date").sort_index()

Empty DataFrame
Columns: []
Index: []

In [136]:
from bson.objectid import ObjectId

for i in _df["_id"]:
    res = client.logistics["alex.habitspunch"].update_one({"_id":ObjectId(i)},{"$set":{"status":"SUCCESS"}})
    print(f"{i} => {res.modified_count}")

5ddfe0fc40333b34f81b20bd => 1

## time

In [49]:
import pandas as pd
timecoll = client.logistics["alex.time"].with_options(codec_options=CodecOptions(tz_aware=True,tzinfo=timezone('Asia/Tokyo')))
time_df = pd.DataFrame([r for r in timecoll.find().sort("date",pymongo.DESCENDING)])