# inspect cards

In [1]:
import pymongo
import pandas as pd
from pytz import timezone
from bson.codec_options import CodecOptions
import matplotlib.pyplot as plt
from pymongo import MongoClient

#global const's
WEEKS = 8
TIMESTAMPS_PER_HOUR = 2
#global var's
local_client = MongoClient('localhost', 27017)
coll = local_client.admin.passwords
doc = coll.find_one({"key":"MONGOMLAB"})
mongopass = doc["value"]
trello_key,trello_token = (local_client.admin.passwords.find_one({"key":k})["value"] for k in ["TRELLOKEY","TRELLOTOKEN"])

In [2]:
import requests
import json

url_stem = "https://api.trello.com"
url = f"{url_stem}/1/tokens/{trello_token}/member"

headers = {
   "Accept": "application/json"
}

query = {
   'key': trello_key,
   'token': trello_token
}

response = requests.request(
   "GET",
   url,
   headers=headers,
   params=query
)

board_ids = json.loads(response.text)["idBoards"]

In [3]:
boards = {b:json.loads(requests.request("GET",f"{url_stem}/1/boards/{b}",headers=headers,params=query).text) for b in board_ids}

In [4]:
import pandas as pd
board_id = "5b9a8552aa36733037ae917e"
lists = {l["id"]:l for l in json.loads(requests.request("GET",f"{url_stem}/1/boards/{board_id}/lists",headers=headers,params={**query,"filter":"all"}).text)}
pd.DataFrame(lists.values())

,id,name,closed,pos,softLimit,idBoard,subscribed
0,5b9a88e3dcd6f9892f47c372,PENDING,False,65535,None,5b9a8552aa36733037ae917e,False
1,5ba121d9717eb68f1713243a,todo,False,81919,None,5b9a8552aa36733037ae917e,False
2,5b9deba8298b842b75c2de29,TODO,False,98303,None,5b9a8552aa36733037ae917e,False
3,5b9e84eb6bd99d50eea0ab64,SPORT,True,114687,None,5b9a8552aa36733037ae917e,False
4,5b9a88e55dd1b019f077c978,DONE,True,131071,None,5b9a8552aa36733037ae917e,False
5,5b9e84f72c2644393805a0cc,einsoch,True,163839,None,5b9a8552aa36733037ae917e,False
6,5bfd1098ffe7563e41e81f69,FAILED2,False,172031,None,5b9a8552aa36733037ae917e,False
7,5b9ef2afac2bb38effad88ed,FAILED,False,196607,None,5b9a8552aa36733037ae917e,False

In [115]:
list_id = "5ba121d9717eb68f1713243a"
cards = {l["id"]:l for l in json.loads(requests.request("GET",f"{url_stem}/1/lists/{list_id}/cards",headers=headers,params=query).text)}

In [142]:
import pandas as pd
import re

_df = pd.DataFrame([c for c in cards.values() if re.match("fix good day, sleep",c["name"]) is not None])
_df if _df.size==0 else _df.loc[:,["id","name","dateLastActivity","shortUrl"]]

,id,name,dateLastActivity,shortUrl
0,5de05753f2335132bc9c335e,"fix good day, sleep",2020-02-02T14:59:42.942Z,https://trello.com/c/bwLo6BBc

In [143]:
for i in _df["id"]:
    res = requests.request("PUT",f"{url_stem}/1/cards/{i}",headers=headers,params={**query,"closed":"true"}).text
    print(f"{i} => {res}")

5de05753f2335132bc9c335e => {"id":"5de05753f2335132bc9c335e","checkItemStates":[],"closed":true,"dateLastActivity":"2020-07-01T08:35:39.947Z","desc":"","descData":null,"dueReminder":null,"idBoard":"5b9a8552aa36733037ae917e","idList":"5ba121d9717eb68f1713243a","idMembersVoted":[],"idShort":16048,"idAttachmentCover":null,"idLabels":["5c36a78df1a04f871b765f6c"],"manualCoverAttachment":false,"name":"fix good day, sleep","pos":139678464,"shortLink":"bwLo6BBc","isTemplate":false,"dueComplete":false,"due":null,"email":null,"shortUrl":"https://trello.com/c/bwLo6BBc","url":"https://trello.com/c/bwLo6BBc/16048-fix-good-day-sleep","cover":{"idAttachment":null,"color":null,"idUploadedBackground":null,"size":"normal","brightness":"light"},"idMembers":[],"badges":{"attachmentsByType":{"trello":{"board":0,"card":0}},"location":false,"votes":0,"viewingMemberVoted":false,"subscribed":false,"fogbugz":"","checkItems":0,"checkItemsChecked":0,"checkItemsEarliestDue":null,"comments":0,"attachments":0,"description":false,"due":null,"dueComplete":false},"subscribed":false,"idChecklists":[],"labels":[{"id":"5c36a78df1a04f871b765f6c","idBoard":"5b9a8552aa36733037ae917e","name":"gym","color":null}]}

# fix mongo

In [7]:
client = MongoClient(f"mongodb://nailbiter:{mongopass}@ds149672.mlab.com:49672/logistics?retryWrites=false")

## habits

In [138]:
import pandas as pd
timecoll = client.logistics["alex.habitspunch"].with_options(codec_options=CodecOptions(tz_aware=True,tzinfo=timezone('Asia/Tokyo')))
habitspunch_df = pd.DataFrame([r for r in timecoll.find().sort("date",pymongo.DESCENDING)])

In [140]:
from datetime import datetime, timedelta
dates = {"2019-11-29"}
_FORMAT = "%Y-%m-%d"
_dates = {*dates,*{(datetime.strptime(ds,_FORMAT)+timedelta(days=1)).strftime(_FORMAT) for ds in dates}}

_df = pd.DataFrame(
    [r 
     for r 
     in habitspunch_df.to_dict(orient="records") 
     if r["name"] in ["good day","sleep"] 
         and r["date"].strftime("%Y-%m-%d") in _dates
         and r["status"]=="FAILURE"
    ])
_df if _df.size==0 else _df.set_index("date").sort_index()

Empty DataFrame
Columns: []
Index: []

In [136]:
from bson.objectid import ObjectId

for i in _df["_id"]:
    res = client.logistics["alex.habitspunch"].update_one({"_id":ObjectId(i)},{"$set":{"status":"SUCCESS"}})
    print(f"{i} => {res.modified_count}")

5ddfe0fc40333b34f81b20bd => 1

## time

In [16]:
import pandas as pd
timecoll = client.logistics["alex.time"].with_options(codec_options=CodecOptions(tz_aware=True,tzinfo=timezone('Asia/Tokyo')))
time_df = pd.DataFrame([r for r in timecoll.find().sort("date",pymongo.DESCENDING)])
time_df.head()

                        _id                             date   category
0  5f0d0394456e536a81c1ab3f 2020-07-14 10:00:04.281000+09:00   parttime
1  5f0d02b6456e536a81c1ab3d 2020-07-14 09:56:22.473000+09:00   parttime
2  5f0cfc88456e536a81c1ab39 2020-07-14 09:30:00.002000+09:00  logistics
3  5f0cf082456e536a81c1ab38 2020-07-14 08:38:42.257000+09:00  logistics
4  5f0ce770456e536a81c1ab36 2020-07-14 08:00:00.006000+09:00   sleeping

In [17]:
from datetime import datetime, date
time_df[[d.date()==date(2019,12,16) for d in time_df["date"] ]]

                            _id                             date   category
10095  5df794f440333b73158fea87 2019-12-16 23:30:12.242000+09:00   parttime
10096  5df78e6840333b73158fea82 2019-12-16 23:02:16.903000+09:00        gym
10097  5df787f740333b73158fea80 2019-12-16 22:34:47.585000+09:00        gym
10098  5df7843540333b73158fea7f 2019-12-16 22:18:45.380000+09:00        gym
10099  5df77a1d40333b73158fea7e 2019-12-16 21:35:41.529000+09:00        gym
10100  5df771ed40333b73158fea7c 2019-12-16 21:00:45.092000+09:00  logistics
10101  5df76e3a40333b73158fea7b 2019-12-16 20:44:58.141000+09:00  logistics
10102  5df763b440333b73158fea77 2019-12-16 20:00:04.383000+09:00   parttime
10103  5df75cbe40333b73158fea75 2019-12-16 19:30:22.683000+09:00   parttime
10104  5df755a340333b73158fea74 2019-12-16 19:00:03.994000+09:00   parttime
10105  5df74fc640333b73158fea70 2019-12-16 18:35:02.179000+09:00   parttime
10106  5df747a340333b73158fea6f 2019-12-16 18:00:19.982000+09:00   parttime
10107  5df7409440333b73158fea6e 2019-12-16 17:30:12.887000+09:00   parttime
10108  5df7398440333b73158fea6c 2019-12-16 17:00:04.229000+09:00   parttime
10109  5df7328240333b73158fea69 2019-12-16 16:30:10.516000+09:00   parttime
10110  5df72ed940333b73158fea67 2019-12-16 16:14:33.332000+09:00   parttime
10111  5df7246b40333b73158fea63 2019-12-16 15:30:03.950000+09:00   parttime
10112  5df71d6440333b73158fea62 2019-12-16 15:00:04.579000+09:00   parttime
10113  5df7170940333b73158fea61 2019-12-16 14:32:57.539000+09:00   parttime
10114  5df70f9d40333b73158fea5e 2019-12-16 14:01:17.672000+09:00   parttime
10115  5df70da740333b73158fea5d 2019-12-16 13:52:55.588000+09:00   parttime
10116  5df7014340333b73158fea5b 2019-12-16 13:00:03.935000+09:00   parttime
10117  5df6fa3c40333b73158fea59 2019-12-16 12:30:04.500000+09:00   parttime
10118  5df6f33340333b73158fea56 2019-12-16 12:00:03.255000+09:00   parttime
10119  5df6ec2c40333b73158fea54 2019-12-16 11:30:04.432000+09:00   parttime
10120  5df6e52440333b73158fea51 2019-12-16 11:00:04.110000+09:00   parttime
10121  5df6e0da40333b73158fea50 2019-12-16 10:41:46.746000+09:00   parttime
10122  5df6d71440333b73158fea4b 2019-12-16 10:00:04.979000+09:00   parttime
10123  5df6d36c40333b73158fea48 2019-12-16 09:44:28.341000+09:00   parttime
10124  5df6c90040333b73158fea46 2019-12-16 09:00:00.030000+09:00  logistics
10125  5df6c1f840333b73158fea45 2019-12-16 08:30:00.025000+09:00   sleeping
10126  5df6baf040333b73158fea41 2019-12-16 08:00:00.041000+09:00   sleeping
10127  5df6b3e840333b73158fea40 2019-12-16 07:30:00.032000+09:00   sleeping
10128  5df6ace040333b73158fea3e 2019-12-16 07:00:00.160000+09:00   sleeping
10129  5df6a5d840333b73158fea3d 2019-12-16 06:30:00.023000+09:00   sleeping
10130  5df69ed040333b73158fea35 2019-12-16 06:00:00.031000+09:00   sleeping
10131  5df697c840333b73158fea34 2019-12-16 05:30:00.025000+09:00   sleeping
10132  5df690c040333b73158fea32 2019-12-16 05:00:00.038000+09:00   sleeping
10133  5df689b840333b73158fea31 2019-12-16 04:30:00.023000+09:00   sleeping
10134  5df682b040333b73158fea2d 2019-12-16 04:00:00.032000+09:00   sleeping
10135  5df67ba840333b73158fea2c 2019-12-16 03:30:00.032000+09:00   sleeping
10136  5df674a040333b73158fea2b 2019-12-16 03:00:00.025000+09:00   sleeping
10137  5df66d9840333b73158fea2a 2019-12-16 02:30:00.050000+09:00   sleeping
10138  5df6669040333b73158fea29 2019-12-16 02:00:00.037000+09:00   sleeping
10139  5df65f8840333b73158fea28 2019-12-16 01:30:00.024000+09:00   sleeping
10140  5df6588040333b73158fea26 2019-12-16 01:00:00.045000+09:00   sleeping
10141  5df6517840333b73158fea24 2019-12-16 00:30:00.036000+09:00     social
10142  5df64a7040333b73158fea20 2019-12-16 00:00:00.035000+09:00     social

In [15]:
from bson.objectid import ObjectId
client.logistics["alex.time"].update_one({"_id":ObjectId("5df6c90040333b73158fea46")},{"$set":{"category":"logistics"}})

## money

In [22]:
import pandas as pd
moneycoll = client.logistics["alex.money"].with_options(codec_options=CodecOptions(tz_aware=True,tzinfo=timezone('Asia/Tokyo')))
money_df = pd.DataFrame([r for r in moneycoll.find().sort("date",pymongo.DESCENDING)])
money_df.head()

,_id,amount,category,date,comment,tags
0,5f0d023d456e536a81c1ab3a,550.0,food,2020-07-14 09:54:21.693000+09:00,,"[tea, macdonalds]"
1,5f0c3637456e536a81c1ab08,50.0,food,2020-07-13 19:23:51.876000+09:00,,"[hotchocolate, automat]"
2,5f0c3582456e536a81c1ab07,688.0,food,2020-07-13 19:20:50.738000+09:00,,"[famima, sandwich]"
3,5f0bef91456e536a81c1aaee,774.0,food,2020-07-13 14:22:25.602000+09:00,,"[famima, sandwich]"
4,5f0bb314456e536a81c1aac1,103.0,fun,2020-07-13 10:04:20.728000+09:00,,[]

In [23]:
from datetime import date
money_df[[d.date()==date(2019,10,27) for d in money_df["date"] ]]

,_id,amount,category,date,comment,tags
929,5db58c1f40333b3252567cb6,492.0,food,2019-10-27 21:22:55.985000+09:00,,[]
930,5db5858d40333b3252567cb4,157.0,food,2019-10-27 20:54:53.626000+09:00,,[subway]
931,5db55c8340333b3252567cad,1080.0,food,2019-10-27 17:59:47.827000+09:00,,[macdonalds]
932,5db5555a40333b3252567ca9,136.0,fun,2019-10-27 17:29:14.614000+09:00,,[subway]
933,5db550c340333b3252567ca8,11.0,fun,2019-10-27 17:09:39.169000+09:00,,[subway]
934,5db549fc40333b3252567ca6,157.0,fun,2019-10-27 16:40:44.964000+09:00,,[subway]
935,5db51ca740333b3252567c9b,170.0,food,2019-10-27 13:27:19.025000+09:00,,[]
936,5db515c740333b3252567c99,760.0,food,2019-10-27 12:57:59.149000+09:00,,[]
937,5db5149540333b3252567c98,1058.0,fun,2019-10-27 12:52:53.737000+09:00,,[jonathan]

In [21]:
from trello_makeup_common import fix_mongo_record
for oid in ["5db549fc40333b3252567ca6"]:
    print(fix_mongo_record(collection_name="alex.money",oid=oid,key="category",value="fun"))

1