In [4]:
import pandas as pd

df = pd.read_json("/Users/nailbiter/Documents/forgithub/ElDrinkoPubBot/.log//DevElDrinkoPubBot_2020-07-19_18:57:59.json",lines=True,orient="records")
df

,instant,thread,level,loggerName,message,endOfBatch,loggerFqcn,threadId,threadPriority,source
0,"{'epochSecond': 1595152679, 'nanoOfSecond': 23...",nl.insomnia247.nailbiter.eldrinkopubbot.App.ma...,INFO,nl.insomnia247.nailbiter.eldrinkopubbot.App,file flag: .tmp/DevElDrinkoPubBot.runs.txt,False,org.apache.logging.log4j.spi.AbstractLogger,14,5,{'class': 'nl.insomnia247.nailbiter.eldrinkopu...
1,"{'epochSecond': 1595152679, 'nanoOfSecond': 30...",nl.insomnia247.nailbiter.eldrinkopubbot.App.ma...,INFO,nl.insomnia247.nailbiter.eldrinkopubbot.App,"save ""98153"" to "".tmp/DevElDrinkoPubBot.runs.txt""",False,org.apache.logging.log4j.spi.AbstractLogger,14,5,{'class': 'nl.insomnia247.nailbiter.eldrinkopu...
2,"{'epochSecond': 1595152679, 'nanoOfSecond': 30...",nl.insomnia247.nailbiter.eldrinkopubbot.App.ma...,INFO,nl.insomnia247.nailbiter.eldrinkopubbot.App,COMMIT_DATA: `beerbot milestone 3990E4599E0BF9...,False,org.apache.logging.log4j.spi.AbstractLogger,14,5,{'class': 'nl.insomnia247.nailbiter.eldrinkopu...
3,"{'epochSecond': 1595152679, 'nanoOfSecond': 30...",nl.insomnia247.nailbiter.eldrinkopubbot.App.ma...,INFO,nl.insomnia247.nailbiter.eldrinkopubbot.App,BOT_NAME: DevElDrinkoPubBot,False,org.apache.logging.log4j.spi.AbstractLogger,14,5,{'class': 'nl.insomnia247.nailbiter.eldrinkopu...
4,"{'epochSecond': 1595152679, 'nanoOfSecond': 92...",nl.insomnia247.nailbiter.eldrinkopubbot.App.ma...,INFO,nl.insomnia247.nailbiter.eldrinkopubbot.eldrin...,botname: DevElDrinkoPubBot,False,org.apache.logging.log4j.spi.AbstractLogger,14,5,{'class': 'nl.insomnia247.nailbiter.eldrinkopu...
...,...,...,...,...,...,...,...,...,...,...
2167,"{'epochSecond': 1595152899, 'nanoOfSecond': 78...",DevElDrinkoPubBot Telegram Executor,INFO,nl.insomnia247.nailbiter.eldrinkopubbot.eldrin...,keyboardKeys: start\n,False,org.apache.logging.log4j.spi.AbstractLogger,25,1,{'class': 'nl.insomnia247.nailbiter.eldrinkopu...
2168,"{'epochSecond': 1595152899, 'nanoOfSecond': 78...",DevElDrinkoPubBot Telegram Executor,INFO,nl.insomnia247.nailbiter.eldrinkopubbot.state_...,"om: ""(TelegramKeyboard(Дякуємо за замовлення!\...",False,org.apache.logging.log4j.spi.AbstractLogger,25,1,{'class': 'nl.insomnia247.nailbiter.eldrinkopu...
2169,"{'epochSecond': 1595152899, 'nanoOfSecond': 78...",DevElDrinkoPubBot Telegram Executor,INFO,nl.insomnia247.nailbiter.eldrinkopubbot.eldrin...,es(340880765): idle,False,org.apache.logging.log4j.spi.AbstractLogger,25,1,{'class': 'nl.insomnia247.nailbiter.eldrinkopu...
2170,"{'epochSecond': 1595152899, 'nanoOfSecond': 78...",DevElDrinkoPubBot Telegram Executor,INFO,nl.insomnia247.nailbiter.eldrinkopubbot.eldrin...,"om(340880765): [{""tag"":""TelegramKeyboard"",""val...",False,org.apache.logging.log4j.spi.AbstractLogger,25,1,{'class': 'nl.insomnia247.nailbiter.eldrinkopu...
2171,"{'epochSecond': 1595152900, 'nanoOfSecond': 31...",DevElDrinkoPubBot Telegram Executor,INFO,nl.insomnia247.nailbiter.eldrinkopubbot.eldrin...,after execute(TelegramKeyboard(Дякуємо за замо...,False,org.apache.logging.log4j.spi.AbstractLogger,25,1,{'class': 'nl.insomnia247.nailbiter.eldrinkopu...

In [33]:
df[[x=="nl.insomnia247.nailbiter.eldrinkopubbot.eldrinko.ElDrinkoPubBot" for x in df["loggerName"]]].loc[:,["instant","message"]].head(20)

,instant,message
4,"{'epochSecond': 1595152679, 'nanoOfSecond': 92...",botname: DevElDrinkoPubBot
5,"{'epochSecond': 1595152681, 'nanoOfSecond': 91...","_config: {""telegram"":{""developerChatIds"":[""340..."
92,"{'epochSecond': 1595152690, 'nanoOfSecond': 11...","edsm: ""choose_phone_number"" -> ""choose_phone_n..."
93,"{'epochSecond': 1595152690, 'nanoOfSecond': 11...",sending `(> updated! now at `beerbot milestone...
94,"{'epochSecond': 1595152733, 'nanoOfSecond': 63...",CreateInputMessage: %s\n
95,"{'epochSecond': 1595152733, 'nanoOfSecond': 63...","config: {""telegram"":{""developerChatIds"":[""3408..."
96,"{'epochSecond': 1595152733, 'nanoOfSecond': 67...",doc: null
97,"{'epochSecond': 1595152733, 'nanoOfSecond': 67...",state: _
101,"{'epochSecond': 1595152733, 'nanoOfSecond': 72...",ss(340880765): _
102,"{'epochSecond': 1595152733, 'nanoOfSecond': 72...","im(340880765): {""userData"":{""chatId"":340880765..."
148,"{'epochSecond': 1595152733, 'nanoOfSecond': 89...",es(340880765): start
149,"{'epochSecond': 1595152733, 'nanoOfSecond': 89...","om(340880765): [{""tag"":""OutputArrayMessage"",""v..."
150,"{'epochSecond': 1595152734, 'nanoOfSecond': 43...",after execute(TelegramOutputMessage(Вітаємо!\n...
151,"{'epochSecond': 1595152734, 'nanoOfSecond': 85...",after execute(TelegramKeyboard(Сьогодні ми про...
152,"{'epochSecond': 1595152737, 'nanoOfSecond': 40...",inline markup: [[InlineKeyboardButton{text='За...
153,"{'epochSecond': 1595152737, 'nanoOfSecond': 40...","SendMessage{chatId='340880765', text='Дивитись..."
154,"{'epochSecond': 1595152738, 'nanoOfSecond': 17...",call_data: 1
155,"{'epochSecond': 1595152738, 'nanoOfSecond': 17...",TelegramKeyboardAnswer(1) to 2033
156,"{'epochSecond': 1595152738, 'nanoOfSecond': 17...","config: {""telegram"":{""developerChatIds"":[""3408..."
157,"{'epochSecond': 1595152738, 'nanoOfSecond': 22...","doc: Document{{_id=5f14195dee365246d5618370, i..."

In [36]:
import re
import pandas as pd
import json
from functools import reduce

_df = df[[x=="nl.insomnia247.nailbiter.eldrinkopubbot.eldrinko.ElDrinkoPubBot" for x in df["loggerName"]]].loc[:,["instant","message"]]
_df = _df[[x[:2] in ["im","om","es","ss"] for x in _df["message"]]]
prog = re.compile("(om|im|es|ss)\([0-9]+\):\s*(.*)")

data = [dict(tag=prog.match(r["message"]).group(1),value=prog.match(r["message"]).group(2)) for r in _df.to_dict(orient="records") if prog.match(r["message"]) is not None]
# print(pd.DataFrame(data).head(10))
def reducer(acc,val):
#     print(f"acc: {acc}")
    l,d = acc
    if val["tag"]=="ss":
        if d:
            l.append(d)
            d = {}
    
    d[val["tag"]] = val["value"]
    return (l,d)
        
l,d = reduce(reducer,data,([],{}))
if d is not None:
    l.append(d)
_df = pd.DataFrame(l)
_df

,ss,im,es,om
0,_,"{""userData"":{""chatId"":340880765,""username"":""Na...",start,"[{""tag"":""OutputArrayMessage"",""value"":[{""tag"":""..."
1,start,"{""userData"":{""chatId"":340880765},""left"":{""msg""...",choose_product_to_see_description,"[{""tag"":""TelegramKeyboard"",""value"":{""msg"":""Зро..."
2,choose_product_to_see_description,"{""userData"":{""chatId"":340880765},""left"":{""msg""...",start,"[{""tag"":""OutputArrayMessage"",""value"":[{""tag"":""..."
3,start,"{""userData"":{""chatId"":340880765},""left"":{""msg""...",choose_product_to_make_order,"[{""tag"":""TelegramKeyboard"",""value"":{""msg"":""Пок..."
4,choose_product_to_make_order,"{""userData"":{""chatId"":340880765},""left"":{""msg""...",choose_amount,"[{""tag"":""TelegramTextOutputMessage"",""value"":{""..."
5,choose_amount,"{""userData"":{""chatId"":340880765,""username"":""Na...",choose_amount,NaN
6,choose_amount,"{""userData"":{""chatId"":340880765,""username"":""Na...",choose_amount,NaN
7,choose_amount,"{""userData"":{""chatId"":340880765,""username"":""Na...",confirm,"[{""tag"":""TelegramKeyboard"",""value"":{""msg"":""Ви ..."
8,confirm,"{""userData"":{""chatId"":340880765},""left"":{""msg""...",choose_product_to_make_order,"[{""tag"":""TelegramKeyboard"",""value"":{""msg"":""Пок..."
9,choose_product_to_make_order,"{""userData"":{""chatId"":340880765},""left"":{""msg""...",choose_amount,"[{""tag"":""TelegramTextOutputMessage"",""value"":{""..."
10,choose_amount,"{""userData"":{""chatId"":340880765,""username"":""Na...",confirm,"[{""tag"":""TelegramKeyboard"",""value"":{""msg"":""Ви ..."
11,confirm,"{""userData"":{""chatId"":340880765},""left"":{""msg""...",delete,"[{""tag"":""TelegramKeyboard"",""value"":{""msg"":""что..."
12,delete,"{""userData"":{""chatId"":340880765},""left"":{""msg""...",confirm,"[{""tag"":""TelegramKeyboard"",""value"":{""msg"":""Ви ..."
13,confirm,"{""userData"":{""chatId"":340880765},""left"":{""msg""...",choose_address,"[{""tag"":""TelegramTextOutputMessage"",""value"":{""..."
14,choose_address,"{""userData"":{""chatId"":340880765,""username"":""Na...",choose_phone_number,"[{""tag"":""TelegramTextOutputMessage"",""value"":{""..."
15,choose_phone_number,"{""userData"":{""chatId"":340880765,""username"":""Na...",choose_phone_number,"[{""tag"":""TelegramTextOutputMessage"",""value"":{""..."
16,choose_phone_number,"{""userData"":{""chatId"":340880765,""username"":""Na...",choose_payment,"[{""tag"":""TelegramKeyboard"",""value"":{""msg"":""Обе..."
17,choose_payment,"{""userData"":{""chatId"":340880765},""left"":{""msg""...",send,"[{""tag"":""TelegramKeyboard"",""value"":{""msg"":""Ви ..."
18,send,"{""userData"":{""chatId"":340880765},""left"":{""msg""...",edit_address,"[{""tag"":""TelegramTextOutputMessage"",""value"":{""..."
19,edit_address,"{""userData"":{""chatId"":340880765,""username"":""Na...",send,"[{""tag"":""TelegramKeyboard"",""value"":{""msg"":""Ви ..."
20,send,"{""userData"":{""chatId"":340880765},""left"":{""msg""...",choose_payment,"[{""tag"":""TelegramKeyboard"",""value"":{""msg"":""Обе..."
21,choose_payment,"{""userData"":{""chatId"":340880765},""left"":{""msg""...",send,"[{""tag"":""TelegramKeyboard"",""value"":{""msg"":""Ви ..."
22,send,"{""userData"":{""chatId"":340880765},""left"":{""msg""...",idle,"[{""tag"":""TelegramKeyboard"",""value"":{""msg"":""Дяк..."
23,idle,"{""userData"":{""chatId"":340880765},""left"":{""msg""...",start,"[{""tag"":""TelegramKeyboard"",""value"":{""msg"":""Сьо..."
24,start,"{""userData"":{""chatId"":340880765},""left"":{""msg""...",choose_product_to_see_description,"[{""tag"":""TelegramKeyboard"",""value"":{""msg"":""Зро..."
25,choose_product_to_see_description,"{""userData"":{""chatId"":340880765,""username"":""Na...",start,"[{""tag"":""OutputArrayMessage"",""value"":[{""tag"":""..."
26,start,"{""userData"":{""chatId"":340880765},""left"":{""msg""...",choose_product_to_make_order,"[{""tag"":""TelegramKeyboard"",""value"":{""msg"":""Пок..."
27,choose_product_to_make_order,"{""userData"":{""chatId"":340880765},""left"":{""msg""...",choose_amount,"[{""tag"":""TelegramTextOutputMessage"",""value"":{""..."
28,choose_amount,"{""userData"":{""chatId"":340880765,""username"":""Na...",confirm,"[{""tag"":""TelegramKeyboard"",""value"":{""msg"":""Ви ..."
29,confirm,"{""userData"":{""chatId"":340880765},""left"":{""msg""...",delete,"[{""tag"":""TelegramKeyboard"",""value"":{""msg"":""что..."
30,delete,"{""userData"":{""chatId"":340880765},""left"":{""msg""...",confirm,"[{""tag"":""TelegramKeyboard"",""value"":{""msg"":""Ви ..."
31,confirm,"{""userData"":{""chatId"":340880765},""left"":{""msg""...",choose_product_to_make_order,"[{""tag"":""TelegramKeyboard"",""value"":{""msg"":""Пок..."
32,choose_product_to_make_order,"{""userData"":{""chatId"":340880765},""left"":{""msg""...",choose_amount,"[{""tag"":""TelegramTextOutputMessage"",""value"":{""..."
33,choose_amount,"{""userData"":{""chatId"":340880765,""username"":""Na...",confirm,"[{""tag"":""TelegramKeyboard"",""value"":{""msg"":""Ви ..."
34,confirm,"{""userData"":{""chatId"":340880765},""left"":{""msg""...",choose_phone_number,"[{""tag"":""TelegramTextOutputMessage"",""value"":{""..."
35,choose_phone_number,"{""userData"":{""chatId"":340880765,""username"":""Na...",choose_payment,"[{""tag"":""TelegramKeyboard"",""value"":{""msg"":""Обе..."
36,choose_payment,"{""userData"":{""chatId"":340880765},""left"":{""msg""...",send,"[{""tag"":""TelegramKeyboard"",""value"":{""msg"":""Ви ..."
37,send,"{""userData"":{""chatId"":340880765},""left"":{""msg""...",idle,"[{""tag"":""TelegramKeyboard"",""value"":{""msg"":""Дяк..."